name: bench (baseline)

on:
  push:
    branches:
      - 'main'

env:
  RUST_VERSION: "1.88.0"

jobs:
  benchmark_base_branch:
    name: Base Benchmark
    permissions:
      checks: write
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
      # First, run all benchmarks "normally", and also with liveness enabled.
      - uses: bencherdev/bencher@main
      - name: Track base branch benchmarks with Bencher
        run: |
          bencher run \
          --project cancel-this \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch main \
          --testbed psyche-compute \
          --threshold-measure latency \
          --threshold-test t_test \
          --threshold-max-sample-size 64 \
          --threshold-upper-boundary 0.99 \
          --thresholds-reset \
          --err \
          --adapter rust_criterion \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          "cargo bench --features=ctrlc --features=pyo3; cargo bench --features=ctrlc --features=pyo3 --features=liveness"